#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

PINNED="8.11.1"
if ! command -v gradle >/dev/null 2>&1; then
  echo "BLOCKED: a real Gradle installation is required to generate the official Wrapper JAR." >&2
  echo "Install Gradle $PINNED (or compatible 8.x), then rerun this script." >&2
  exit 20
fi

GV="$(gradle --version | awk '/^Gradle /{print $2; exit}')"
if [[ "$GV" != "$PINNED" ]]; then
  echo "BLOCKED: expected Gradle $PINNED to generate the pinned wrapper; found $GV." >&2
  exit 21
fi

gradle --no-daemon wrapper --gradle-version "$PINNED" --distribution-type bin

# The Wrapper JAR must be generated by Gradle; never synthesize or replace it.
[[ -x "$ROOT/gradlew" ]] || { echo "ERROR: gradlew was not generated" >&2; exit 22; }
[[ -f "$ROOT/gradlew.bat" ]] || { echo "ERROR: gradlew.bat was not generated" >&2; exit 23; }
[[ -f "$ROOT/gradle/wrapper/gradle-wrapper.jar" ]] || { echo "ERROR: Wrapper JAR was not generated" >&2; exit 24; }
[[ -f "$ROOT/gradle/wrapper/gradle-wrapper.properties" ]] || { echo "ERROR: Wrapper properties were not generated" >&2; exit 25; }

python3 tools/verify_build_reproducibility.py
echo "PASS: official Gradle Wrapper generated and reproducibility contract passes."
